package mj559.euler.problems;

import mj559.euler.util.Timer;

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous 
 * two terms. By starting with 1 and 2, the first 10 terms will be:
*
* 			1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
*
* By considering the terms in the Fibonacci sequence whose values do not exceed 
* four million, find the sum of the even-valued terms.
*/

public class Problem2 implements Problem {

	@Override
	public void solve() {
		Timer.start();
		int n = 1, m = 1;
		long result = 0;
		
		while (n < 4000000){
			
			if (n % 2 == 0){
				result += n;
			}
			
			int tmp = n + m;
			n = m; m = tmp;

		}
		long time = Timer.stop();
		
		System.out.println("The solution is: " +  result);
		System.out.println("Took " + time + "ms.");
	}

	public static void main(String[] args) {
		Problem p = new Problem2();
		p.solve();

	}

}
